trigger:
        - main

        pool:
          vmImage: 'windows-latest' 

        variables:
          imageName: 'pipelines-javascript-docker (1)'

        steps:
        - task: Docker@2
          displayName: Build an image
          inputs:
            repository: $(imageName)
            command: build
            Dockerfile: app/Dockerfile